// src/components/header.tsx
import classnames from 'classnames';
import { FC, useMemo } from 'react';

interface Props {
	show?: 'mobile' | 'tablet';
}

export const Header: FC<Props> = ({ show = 'mobile' }) => {
	const showMobile = show === 'mobile';
	const showTablet = show === 'tablet';

	const classes = useMemo(() => {
		return classnames(
			'items-center',
			'justify-center',
			'bg-primary',
			'text-white',
			'dark:bg-zinc-950',
			'dark:text-primary',
			showMobile && ['flex', 'sm:hidden'],
			showTablet && ['hidden', 'sm:flex'],
		);
	}, [showMobile, showTablet]);

	return (
		<div className={classes}>
			<h1 className="p-3 text-xl font-bold tracking-wide">been</h1>
		</div>
	);
};

// src/app/header/header.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

@Component({
	selector: 'app-header',
	templateUrl: './header.component.html',
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeaderComponent {
	@Input()
	show: 'mobile' | 'tablet' = 'mobile';

	get showMobile(): boolean {
		return this.show === 'mobile';
	}

	get showTablet(): boolean {
		return this.show === 'tablet';
	}
}

<div
	class="items-center justify-center bg-primary text-white sm:hidden dark:bg-zinc-950 dark:text-primary"
	[ngClass]="{
		flex: showMobile,
		'sm:hidden': showMobile,
		hidden: showTablet,
		'sm:flex': showTablet,
	}"
>
	<h1 class="p-3 text-xl font-bold tracking-wide">been</h1>
</div>
