// src/app/menu/Menu.tsx
import { type FC, ReactNode, useCallback, useMemo, useState } from 'react';

import { useCountries } from '../hooks/useCountries';
import { Country } from '../models/country';

interface Props {
	children: ReactNode;
}

export const Menu: FC<Props> = ({ children }) => {
	const { regions, addCountry, removeCountry } = useCountries();

	const [search, setSearch] = useState('');

	const filteredRegions = useMemo(() => {
		const s = search.trim().toLowerCase();
		if (!s) {
			return regions;
		}
		return regions
			.map((region) => ({
				...region,
				values: region.values.filter(({ name }) =>
					name.toLowerCase().includes(s),
				),
			}))
			.filter((region) => region.values.length > 0);
	}, [search, regions]);

	const toggleCountry = useCallback(
		(country: Country) => {
			if (country.selected) {
				removeCountry(country.iso3166);
			} else {
				addCountry(country.iso3166);
			}
		},
		[addCountry, removeCountry],
	);

	return (
		<>
			{children}
			<form className="border-t-2 border-zinc-200 sm:border-t-0 dark:border-zinc-700">
				<label htmlFor="search" className="sr-only">
					Search
				</label>
				<input
					id="search"
					className="w-full border-none bg-white px-4 py-2 text-zinc-900 focus:ring-2 focus:ring-inset focus:ring-primary/50 dark:bg-zinc-900 dark:text-white"
					type="text"
					placeholder="Search..."
					value={search}
					onChange={(e) => {
						setSearch(e.target.value);
					}}
				/>
			</form>
			{filteredRegions.length === 0 ? (
				<div className="m-4 h-full text-center font-medium">
					No results!
				</div>
			) : (
				<ul className="h-full overflow-y-auto">
					{filteredRegions.map((region) => (
						<li key={region.name}>
							<h2 className="bg-zinc-200 p-4 font-medium dark:bg-zinc-800">
								{region.name || 'Other'}
							</h2>
							<ul className="divide-y divide-zinc-100 dark:divide-zinc-800">
								{region.values.map((country) => (
									<li
										key={country.iso3166}
										className="hover:bg-zinc-50 dark:hover:bg-zinc-800"
									>
										<label className="flex items-center px-4 py-1">
											<input
												id={country.iso3166}
												className="my-0 me-2 size-4 rounded border-zinc-400 bg-zinc-50 text-primary focus:ring-2 focus:ring-primary/50 active:ring-primary dark:border-zinc-600 dark:bg-zinc-900"
												type="checkbox"
												checked={country.selected}
												onChange={() => {
													toggleCountry(country);
												}}
											/>
											<span>{country.name}</span>
										</label>
									</li>
								))}
							</ul>
						</li>
					))}
				</ul>
			)}
		</>
	);
};

// src/app/menu/menu.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	HostBinding,
	Inject,
} from '@angular/core';
import { FormControl } from '@angular/forms';
import {
	type Observable,
	concat,
	defer,
	distinctUntilChanged,
	map,
	of,
	switchMap,
} from 'rxjs';

import type { Country } from '../models/country';
import type { Region } from '../models/region';
import { CountriesService } from '../services/countries.service';

@Component({
	selector: 'app-menu',
	templateUrl: './menu.component.html',
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MenuComponent {
	@HostBinding('class')
	class = 'flex flex-col';

	searchControl = new FormControl('', { nonNullable: true });

	constructor(
		@Inject(CountriesService) private countriesService: CountriesService,
	) {}

	get filteredRegions$(): Observable<Region[]> {
		return concat(
			defer(() => of(this.searchControl.value)),
			this.searchControl.valueChanges,
		).pipe(
			distinctUntilChanged(),
			map((search) => search.trim().toLowerCase()),
			switchMap((search) =>
				this.countriesService.regions$.pipe(
					map((regions) =>
						search
							? regions.map((region) => ({
									...region,
									values: region.values.filter(({ name }) =>
										name.toLowerCase().includes(search),
									),
								}))
							: regions,
					),
				),
			),
		);
	}

	toggleCountry(country: Country): void {
		if (country.selected) {
			this.countriesService.removeCountry(country.iso3166);
		} else {
			this.countriesService.addCountry(country.iso3166);
		}
	}
}

<ng-content></ng-content>
<form class="border-t-2 border-zinc-200 sm:border-t-0 dark:border-zinc-700">
	<label for="search" class="sr-only">Search</label>
	<input
		id="search"
		class="w-full border-none bg-white px-4 py-2 text-zinc-900 focus:ring-2 focus:ring-inset focus:ring-primary/50 dark:bg-zinc-900 dark:text-white"
		type="text"
		placeholder="Search..."
		[formControl]="searchControl"
	/>
</form>
@if (filteredRegions$ | async; as filteredRegions) {
	@if (filteredRegions.length === 0) {
		<div class="m-4 h-full text-center font-medium">No results!</div>
	} @else {
		<ul class="h-full overflow-y-auto">
			@for (region of filteredRegions; track region.name) {
				<li>
					<h2 class="bg-zinc-200 p-4 font-medium dark:bg-zinc-800">
						{{ region.name || 'Other' }}
					</h2>
					<ul class="divide-y divide-zinc-100 dark:divide-zinc-800">
						@for (country of region.values; track country.iso3166) {
							<li class="hover:bg-zinc-50 dark:hover:bg-zinc-800">
								<label class="flex items-center px-4 py-1">
									<input
										[id]="country.iso3166"
										class="my-0 me-2 size-4 rounded border-zinc-400 bg-zinc-50 text-primary focus:ring-2 focus:ring-primary/50 active:ring-primary dark:border-zinc-600 dark:bg-zinc-900"
										type="checkbox"
										[ngModel]="country.selected"
										(ngModelChange)="toggleCountry(country)"
									/>
									<span>{{ country.name }}</span>
								</label>
							</li>
						}
					</ul>
				</li>
			}
		</ul>
	}
} @else {
	<div role="status" class="flex h-full items-center justify-center">
		<svg
			aria-hidden="true"
			class="size-8 animate-spin fill-primary text-gray-200 dark:text-gray-600"
			viewBox="0 0 100 101"
			fill="none"
			xmlns="http://www.w3.org/2000/svg"
		>
			<path
				d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
				fill="currentColor"
			/>
			<path
				d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
				fill="currentFill"
			/>
		</svg>
		<span class="sr-only">Loading...</span>
	</div>
}
