// src/app/map/map.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	HostBinding,
	type OnDestroy,
	type OnInit,
	inject,
} from '@angular/core';
import { type Map } from 'mapbox-gl';
import { type Observable, distinctUntilChanged, fromEvent, map } from 'rxjs';
import { SubSink } from 'subsink';

import {
	type Coordinate,
	type NestedCoordinates,
	getCoordsCenter,
} from '../helpers';
import { WindowRef } from '../refs/window.ref';
import { CountriesService } from '../services/countries.service';

@Component({
	selector: 'app-map',
	templateUrl: './map.component.html',
	styleUrl: './map.component.scss',
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MapComponent implements OnInit, OnDestroy {
	private readonly countriesService = inject(CountriesService);
	private readonly windowRef = inject(WindowRef);

	@HostBinding('class')
	class = 'flex flex-col';

	readonly darkThemeUrl = 'mapbox://styles/mapbox/dark-v11';
	readonly lightThemeUrl = 'mapbox://styles/mapbox/light-v11';
	readonly prefersDark = this.windowRef.window.matchMedia(
		'(prefers-color-scheme: dark)',
	).matches;

	map?: Map;
	center?: Coordinate;
	minZoom = 1.8;

	private _subs = new SubSink();

	get countriesSelected$(): Observable<string[]> {
		return this.countriesService.countries$.pipe(
			map((countries) =>
				countries.filter((c) => c.selected).map((c) => c.iso3166),
			),
		);
	}

	get prefersDark$(): Observable<boolean> {
		return fromEvent<MediaQueryListEvent>(
			this.windowRef.window.matchMedia('(prefers-color-scheme: dark)'),
			'change',
		).pipe(
			map((event) => event.matches),
			distinctUntilChanged(),
		);
	}

	ngOnInit(): void {
		this._subs.sink = this.countriesService.focus$.subscribe((country) => {
			const query = this.map?.querySourceFeatures('countries', {
				sourceLayer: 'country_boundaries',
				filter: ['==', ['get', 'iso_3166_1'], country],
			});
			const feature = query?.[0];
			if (feature) {
				const { coordinates } = feature.geometry as {
					coordinates?: NestedCoordinates;
				};
				if (coordinates) {
					this.center = getCoordsCenter(coordinates);
				}
			}
		});

		this._subs.sink = this.prefersDark$.subscribe((prefersDark) => {
			this.map?.setStyle(
				prefersDark ? this.darkThemeUrl : this.lightThemeUrl,
			);
		});
	}

	ngOnDestroy(): void {
		this._subs.unsubscribe();
	}

	onMapLoad(map: Map): void {
		this.map = map;
	}
}

<div class="flex items-center justify-center bg-primary text-white sm:hidden">
	<h1 class="p-3 text-xl font-bold tracking-wide">been</h1>
</div>
<mgl-map
	logoPosition="bottom-right"
	[attributionControl]="false"
	[minZoom]="minZoom"
	[style]="'mapbox://styles/mapbox/light-v11'"
	[center]="center"
	[zoom]="[minZoom]"
	[antialias]
	(mapLoad)="onMapLoad($event.target)"
>
	<mgl-vector-source
		id="countries"
		url="mapbox://mapbox.country-boundaries-v1"
	></mgl-vector-source>
	<mgl-control mglNavigation></mgl-control>
	<mgl-layer
		id="3d-buildings"
		type="fill-extrusion"
		source="composite"
		sourceLayer="building"
		[minzoom]="15"
		[filter]="['==', 'extrude', 'true']"
		[paint]="{
			'fill-extrusion-color': [
				'case',
				[
					'in',
					['get', 'iso_3166_1'],
					['literal', (countriesSelected$ | async) ?? []]
				],
				'#fd7e14',
				'#aaa'
			],
			'fill-extrusion-height': [
				'interpolate',
				['linear'],
				['zoom'],
				15,
				0,
				15.05,
				['get', 'height']
			],
			'fill-extrusion-base': [
				'interpolate',
				['linear'],
				['zoom'],
				15,
				0,
				15.05,
				['get', 'min_height']
			],
			'fill-extrusion-opacity': 0.6
		}"
	></mgl-layer>
	<mgl-layer
		id="visited-countries"
		type="fill"
		source="countries"
		sourceLayer="country_boundaries"
		[before]="'national-park'"
		[filter]="[
			'in',
			['get', 'iso_3166_1'],
			['literal', (countriesSelected$ | async) ?? []]
		]"
		[paint]="{ 'fill-color': '#fd7e14', 'fill-opacity': 0.6 }"
	></mgl-layer>
</mgl-map>

// src/components/map.tsx
import { centerOfMass, featureCollection } from '@turf/turf';
import { type FC, ReactNode, useEffect, useMemo, useRef } from 'react';
import {
	Layer,
	MapRef,
	NavigationControl,
	Map as ReactMapGL,
	Source,
} from 'react-map-gl';

import { useCountries } from '../contexts/countries-context';
import { useMatchMedia } from '../hooks/use-match-media';

const apiKeyMapbox = import.meta.env['VITE_API_KEY_MAPBOX'] as
	| string
	| undefined;
const darkThemeUrl = 'mapbox://styles/mapbox/dark-v11';
const lightThemeUrl = 'mapbox://styles/mapbox/light-v11';

const minZoom = 1.8;

interface Props {
	header: ReactNode;
}

export const Map: FC<Props> = ({ header }) => {
	const mapRef = useRef<MapRef>(null);
	const prefersDark = useMatchMedia('(prefers-color-scheme: dark)');

	const { countries, focus } = useCountries();

	const selectedCountries = useMemo(() => {
		return countries.filter((c) => c.selected).map((c) => c.iso3166);
	}, [countries]);

	useEffect(() => {
		if (!focus || !mapRef.current) {
			return;
		}
		const { current: map } = mapRef;
		const features = map.querySourceFeatures('countries', {
			sourceLayer: 'country_boundaries',
			filter: ['==', ['get', 'iso_3166_1'], focus],
		});
		if (features.length > 0) {
			const { geometry } = centerOfMass(featureCollection(features));
			const [lat = 0, lon = 0] = geometry.coordinates;
			map.flyTo({ center: [lat, lon], zoom: minZoom });
		}
	}, [focus, mapRef]);

	if (!apiKeyMapbox) {
		return (
			<div className="flex size-full items-center justify-center bg-primary text-white dark:bg-zinc-950 dark:text-primary">
				<div>Whoops, something has gone wrong.</div>
			</div>
		);
	}

	return (
		<>
			{header}
			<ReactMapGL
				mapboxAccessToken={apiKeyMapbox}
				mapStyle={prefersDark ? darkThemeUrl : lightThemeUrl}
				antialias
				attributionControl={false}
				minZoom={minZoom}
				ref={mapRef}
			>
				<NavigationControl />
				<Source
					id="countries"
					type="vector"
					url="mapbox://mapbox.country-boundaries-v1"
				/>
				{/* eslint-disable @typescript-eslint/naming-convention -- mapbox-gl has specific property names we must use */}
				<Layer
					id="visited-countries"
					type="fill"
					source="countries"
					source-layer="country_boundaries"
					beforeId="national-park"
					filter={[
						'in',
						['get', 'iso_3166_1'],
						['literal', selectedCountries],
					]}
					paint={{ 'fill-color': '#fd7e14', 'fill-opacity': 0.6 }}
				/>
				<Layer
					id="buildings"
					type="fill-extrusion"
					source="composite"
					source-layer="building"
					minzoom={15}
					filter={['==', 'extrude', 'true']}
					paint={{
						'fill-extrusion-color': [
							'case',
							[
								'in',
								['get', 'iso_3166_1'],
								['literal', selectedCountries],
							],
							'#fd7e14',
							'#fd7e14',
						],
						'fill-extrusion-height': [
							'interpolate',
							['linear'],
							['zoom'],
							15,
							0,
							15.05,
							['get', 'height'],
						],
						'fill-extrusion-base': [
							'interpolate',
							['linear'],
							['zoom'],
							15,
							0,
							15.05,
							['get', 'min_height'],
						],
						'fill-extrusion-opacity': 0.6,
					}}
				/>
				{/* eslint-enable @typescript-eslint/naming-convention */}
			</ReactMapGL>
		</>
	);
};
